# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: K4jQwFf1Iu0RpECNnEIXT1wsLEMrN1Xy
            client-secret: NWSyF6Jr3-d0fm14FI24X-SbCKsOMFJ-yvfy6fbqERByfeMkqy79hKRUV1dHmG3Y
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-uwik11si3yyowpra.us.auth0.com/

